#!/usr/bin/env python3
# Copyright (c) 2026 黑沐. Generator: MIT; generated font data: SIL OFL 1.1.
"""Portable, reproducible Syna UI bitmap subsets from a bundled OFL font.
Requires Pillow and fonttools. No Windows system fonts are used.
"""
import hashlib
import gzip
import json
import sys
from pathlib import Path
from PIL import ImageFont
from fontTools.ttLib import TTFont

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
FONT=HERE/'fonts/NotoSansCJKsc-Regular.otf'
OUTPUT=HERE.parent/'src/assets'
OVERLAY=ROOT/'xiaozhi/overlay/main/boards/waveshare/esp32-s3-rlcd-4.2'
font_data=TTFont(FONT)
coverage=font_data.getBestCmap()
LATIN=HERE/'fonts/Arimo-Regular.ttf'
PIXEL=HERE/'fonts/unifont-16.0.04.hex.gz'
pixel_glyphs={int(a,16):bytes.fromhex(b) for a,b in
    (line.split(':') for line in gzip.decompress(PIXEL.read_bytes()).decode().splitlines())}

def rows(values, width=16):
    return '\n'.join('    '+', '.join(values[i:i+width])+',' for i in range(0,len(values),width))

def generate(name,size,height,points,fallback=None,font_path=FONT,pixel=False):
    cmap=pixel_glyphs if pixel else TTFont(font_path).getBestCmap()
    points=sorted(cp for cp in set(points) if cp in cmap)
    font=ImageFont.truetype(str(font_path),size)
    bitmap=[];descriptors=['    {0},']
    for cp in points:
        char=chr(cp)
        # Ask FreeType for a monochrome glyph directly. Thresholding a grayscale
        # glyph loses small-size stem alignment and produces uneven strokes.
        if pixel:
            data=pixel_glyphs[cp];w=len(data)//2;h=16;x=0;bottom=2
            bits=[(v>>shift)&1 for v in data for shift in range(7,-1,-1)]
            advance=w*16
        else:
            mask,(x,y)=font.getmask2(char,mode='1',anchor='ls')
            w,h=mask.size;bottom=y+h
            bits=[1 if v else 0 for v in mask] if w*h else []
            advance=round(font.getlength(char))*16
        offset=len(bitmap)
        if not any(bits):w=h=0;x=bottom=0;bits=[]
        for i in range(0,len(bits),8):
            chunk=bits[i:i+8];bitmap.append(sum(bit<<(7-j) for j,bit in enumerate(chunk)))
        descriptors.append('    {.bitmap_index=%d, .adv_w=%d, .box_w=%d, .box_h=%d, .ofs_x=%d, .ofs_y=%d},'%
            (offset,advance,w,h,x,-bottom))
    start=points[0]
    origin='GNU Unifont 16.0.04' if pixel else ('Arimo' if font_path==LATIN else 'Noto Sans CJK SC')
    header='/* Syna UI bitmap subset derived from '+origin+'''.
 * Font data licensed under SIL OFL 1.1; see assets/fonts/SOURCE.md and licenses.
 * Generated by assets/generate_ui_fonts.py. Preserve upstream font attribution.
 */
#include "lvgl.h"
'''
    if fallback:header+='extern const lv_font_t '+fallback+';\n'
    text=header+'static const uint8_t bitmap[] = {\n'+rows([f'0x{x:02x}' for x in bitmap])+'\n};\n'
    text+='static const lv_font_fmt_txt_glyph_dsc_t glyphs[] = {\n'+'\n'.join(descriptors)+'\n};\n'
    text+='static const uint16_t unicode_list[] = {\n'+rows([str(cp-start) for cp in points])+'\n};\n'
    text+='static const lv_font_fmt_txt_cmap_t cmaps[] = {{.range_start=%d, .range_length=%d, .glyph_id_start=1, .unicode_list=unicode_list, .list_length=%d, .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};\n'%(start,points[-1]-start+1,len(points))
    text+='static const lv_font_fmt_txt_dsc_t dsc = {.glyph_bitmap=bitmap, .glyph_dsc=glyphs, .cmaps=cmaps, .cmap_num=1, .bpp=1, .bitmap_format=LV_FONT_FMT_TXT_PLAIN};\n'
    text+='const lv_font_t '+name+' = {.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt, .line_height=%d, .base_line=3, .subpx=LV_FONT_SUBPX_NONE, .underline_thickness=1, '%height
    if fallback:text+='.fallback=&'+fallback+', '
    text+='.dsc=&dsc};\n'
    for directory in (OUTPUT,OVERLAY):(directory/(name+'.c')).write_text(text)
    print(name,len(points),'glyphs',len(bitmap),'bitmap bytes')

brand_text='夏柠 · 黑沐'
if '--brand-only' in sys.argv:
    generate('ui_font_28_brand',28,34,map(ord,brand_text))
    raise SystemExit(0)

latin=list(range(32,127))+[176,183]
for size,height in [(11,14),(14,17),(18,21)]:generate(f'ui_font_{size}_regular',size,height,latin,font_path=LATIN)
# Keep the public symbol for compatibility; its Chinese glyphs are native 16px,
# with the existing 17px line height. Do not rescale these hand-aligned pixels.
cjk=[cp for cp in json.loads((HERE/'fonts/cjk-codepoints.json').read_text()) if cp in coverage and cp not in latin]
assert all(cp in pixel_glyphs for cp in cjk), 'Pixel font must preserve existing CJK coverage'
generate('ui_font_14_cjk',16,17,cjk,'ui_font_14_regular',pixel=True)
generate('ui_font_28_brand',28,34,map(ord,brand_text))
rights=sorted({r.toUnicode() for r in font_data['name'].names if r.nameID in (0,13,14)})
# SOURCE.md is maintained with notices for all three upstream fonts.
